= electron-lisp-boilerplate
v0.0.1
mikel evins <mikel@evins.net>
:toc:

== Overview

An Electron boilerplate that sets up an app whose application logic is handled by a Lisp child process.

== Prerequisites

. node and npm
. electron-packager
. sbcl
. quicklisp

== Usage

. Clone electron-lisp-boilerplate
. Remove the .git subdirectory
. Rename the project from electron-lisp-boilerplate to the name of your project +
You will have to search for all occurrences of "electron-lisp-boilerplate" in the project and replace them. +
TODO: automate renaming.
. Run the command `./buildapp.sh`

The `buildapp.sh` command 

. uses sbcl to build the `lisapp` program from sources in the `lisp` subdirectory
. installs the needed Node modules in your project's directory
. uses electron-packager to build the Electron app to the subdirectory `electron-lisp-boilerplate-<DELIVERY-TARGET>`

You can remove the files generated by the build by running the command `./clean.sh`

== Building your app

The built app is an Electron application that spawns a Lisp process when it launches. It then sends an HTTP request to its child Lisp process, which returns an HTML document that contains the initial UI of the application. The Electron process presents the UI, and the Lisp child process handles requests generated by interactions with the UI.

To build your application, write Lisp code in the `lisp` subdirectory, implementing HTTP handlers using Hunchentoot's handler framework. To add UI elements, write Lisp code that embeds those elements in the pages served by Hunchentoot.

This version of the boilerplate uses https://htmx.org/[htmx] to build HTML widgets, and the https://github.com/n-elements/core[native-elements CSS framework] for styling.